<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * Service to interface with the Groq LLM API, acting as the primary cognitive engine.
 * Provides fallback mechanics if an API key is unconfigured.
 */
class GroqService
{
    protected ?string $apiKey;

    protected string $baseUrl = 'https://api.groq.com/openai/v1';

    public function __construct()
    {
        // Retrieve Groq API key from environment configuration
        $this->apiKey = config('services.groq.api_key', env('GROQ_API_KEY'));
    }

    /**
     * Send messages to Groq LLM API with formatted system prompts.
     *
     * @param  array  $messages  Complete conversation history
     * @param  string  $systemPrompt  Dynamic prompt generated by CognitiveRotationService
     * @param  float  $temperature  Model temperature setting for creative empathy
     * @return string Generated response from LLM or fallback engine
     */
    public function generateCompletion(array $messages, string $systemPrompt, float $temperature = 0.7): string
    {
        if (empty($this->apiKey)) {
            Log::warning('GROQ_API_KEY not set. Using empathetic pedagogical fallback engine.');

            return $this->fallbackResponse($messages, $systemPrompt);
        }

        try {
            // Prepend system prompt to conversation message array
            $formattedMessages = array_merge(
                [['role' => 'system', 'content' => $systemPrompt]],
                $messages
            );

            // Execute HTTP request to Groq API endpoint enforcing JSON object output
            $model = config('services.groq.model', env('GROQ_MODEL', 'openai/gpt-oss-120b'));

            $response = Http::withHeaders([
                'Authorization' => 'Bearer '.$this->apiKey,
                'Content-Type' => 'application/json',
            ])->timeout(30)->post("{$this->baseUrl}/chat/completions", [
                'model' => $model,
                'messages' => $formattedMessages,
                'response_format' => ['type' => 'json_object'],
                'temperature' => $temperature,
                'max_tokens' => 1024,
            ]);

            if ($response->successful()) {
                return $response->json('choices.0.message.content') ?? $this->fallbackResponse($messages, $systemPrompt);
            }

            Log::error('Groq API Error: '.$response->body());

            return $this->fallbackResponse($messages, $systemPrompt);
        } catch (\Throwable $e) {
            Log::error('Groq Service Exception: '.$e->getMessage());

            return $this->fallbackResponse($messages, $systemPrompt);
        }
    }

    /**
     * Empathetic local response fallback generator returning structured JSON if API service is unreachable.
     */
    protected function fallbackResponse(array $messages, string $systemPrompt): string
    {
        $rawMsg = end($messages)['content'] ?? '';
        $lastUserMsg = strtolower($rawMsg);
        $isEnglish = preg_match('/^[a-zA-Z0-9\s\?\!\,\.\'\"]+$/', trim($rawMsg));

        if (str_contains($lastUserMsg, 'fail') || str_contains($lastUserMsg, 'stuck') || str_contains($lastUserMsg, 'overwhelmed')) {
            $msg = $isEnglish
                ? "I deeply understand the heavy weight you're carrying right now. When your mind feels overloaded, it is completely natural to hit a pause. You don't have to carry all of this alone.\n\nLet's break down what's in front of you. What is the single smallest task on your desk right now that we can explore together?"
                : "我能深深體會你現在面對考試壓力時的沉重感。當大腦超載時出現停滯感是很正常的，我們不需要獨自承擔全部壓力。\n\n讓我們把眼前的任務拆解成小步。你現在桌上哪一個最小的任務是我們可以一起探索的？";
            $scores = ['Ti' => 12, 'Te' => 14, 'Fi' => 26, 'Fe' => 10, 'Ni' => 18, 'Ne' => 16, 'Si' => 12, 'Se' => 8];
            $primary = 'Fi';
            $target = 'Te';
        } elseif (str_contains($lastUserMsg, 'math') || str_contains($lastUserMsg, 'logic') || str_contains($lastUserMsg, 'problem')) {
            $msg = $isEnglish
                ? "When we get caught up in analyzing complex problems, inner logic can spiral into overthinking. Let's ground this: instead of looking at the entire syllabus, let's step back and look at the foundation. What key concept do you feel most confident about?"
                : '當我們沉浸在分析複雜問題時，內在的邏輯有時會陷入過度思考。讓我們冷靜下來：與其看整份試卷或大綱，不如先看基石。目前哪一個概念是你最有把握的？';
            $scores = ['Ti' => 28, 'Te' => 12, 'Fi' => 10, 'Fe' => 8, 'Ni' => 16, 'Ne' => 14, 'Si' => 10, 'Se' => 8];
            $primary = 'Ti';
            $target = 'Te';
        } else {
            $msg = $isEnglish
                ? "I am listening closely to what you are sharing. You don't have to carry all this pressure by yourself. Let's take a quiet breath together and organize your thoughts step by step so you feel supported and grounded."
                : '我正用心聆聽你的分享。你不需要一個人背負所有焦慮，讓我們一起深呼吸，一步步整理你的想法，感受支持與安心。';
            $hash = crc32($lastUserMsg);
            $scores = [
                'Fi' => 22 + ($hash % 7),
                'Fe' => 14 + (($hash >> 2) % 7),
                'Ti' => 16 + (($hash >> 4) % 7),
                'Te' => 12 + (($hash >> 6) % 7),
                'Ni' => 18 + (($hash >> 8) % 7),
                'Ne' => 17 + (($hash >> 10) % 7),
                'Si' => 10 + (($hash >> 12) % 7),
                'Se' => 11 + (($hash >> 14) % 7),
            ];
            $primary = 'Fi';
            $target = 'Fe';
        }

        return json_encode([
            'message' => $msg,
            'scores' => $scores,
            'dominant_function' => $primary,
            'rotation_target' => $target,
            'rotation_vector' => "{$primary} -> {$target}",
            'in_loop' => false,
            'emotional_clarity_score' => 0.85,
        ], JSON_UNESCAPED_UNICODE);
    }
}
